export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_FILTERED_USERS_SUCCESS = "LOAD_FILTERED_USERS_SUCCESS"
export const SAVE_SESSION = "SAVE_SESSION"
export const SAVE_CHATS = "SAVE_CHATS"